name: Afk-Bot

on:
  schedule:
    - cron: "0 */5 * * *"   # runs every 5 hours
  workflow_dispatch:
  
concurrency:
  group: Afk-bot
  cancel-in-progress: true
    
jobs:
  run-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'   # using Node.js 14.x

      - name: Install mineflayer
        run: npm install mineflayer
      
      - name: Install dependencies
        run: npm install

      - name: Run script
        run: |
          sleep 30
          node index.js
